# -*- coding: utf-8 -*-
"""Motivation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5TqYPVBHK-yqVIuWhgDVJ_dSponhSat
"""

!pip install openai gradio

import openai
import gradio as gr

# Set your OpenAI API key here or set as environment variable OPENAI_API_KEY
openai.api_key = "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"

import random

def generate_motivation(mood_or_situation):
    sample_quotes = [
        "Keep pushing forward; your efforts will pay off!",
        "Every challenge is an opportunity to grow stronger.",
        "Believe in yourself, because you are capable of amazing things.",
        "Stay positive, stay focused, and never give up!",
        "Your journey is unique—embrace every step with courage."
    ]
    return random.choice(sample_quotes)




# Gradio UI
iface = gr.Interface(
    fn=generate_motivation,
    inputs=gr.Textbox(label="How are you feeling or what do you need motivation for?", placeholder="e.g., feeling anxious, need focus"),
    outputs=gr.Textbox(label="Your Daily Motivation"),
    title="Daily Motivation Generator",
    description="Enter your current mood or situation, and get a personalized motivational quote.",
    examples=[
        ["feeling anxious"],
        ["need focus for work"],
        ["feeling overwhelmed"],
        ["preparing for an important interview"],
    ]
)

iface.launch(share=True)